export const ORDER_CREATE_REQUEST = "PRODUCT_LIST_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAILL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESETL";

export const ORDER_DETAILS_REQUEST = "PRODUCT_LIST_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAILL";
